name:                picTool
version:             0.1.0.0
github:              "githubuser/picTool"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/picTool#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- strings
- vector
- directory
- time
- mtl
- data-default-class
- http-conduit
- http-client
- aeson
- aeson-pretty
- lens-aeson
- lens
- authenticate-oauth
- attoparsec
- extensible
- hspec

library:
  source-dirs: src

executables:
  picTool-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - picTool

tests:
  picTool-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - picTool
